version: '3.9'
services:
  wordpress:
    # default port 9000 (FastCGI)
    image: wordpress:5-fpm
    container_name: wp-wordpress
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    
  wordpress2:
    # default port 9000 (FastCGI)
    image: wordpress:5-fpm
    container_name: wp-wordpress2
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database2
    volumes:
      - ${WORDPRESS_LOCAL_HOME2}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG2}:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST2}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME2}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER2}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD2}

  database:
    # default port 3306
    image: mysql:8
    container_name: wp-database
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    container_name: wp-nginx
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
    ports:
      - "80:80"    # http
      - "443:443"   # https
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/
      - ${CERTBOT_CONFIG}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx
    
   phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
     networks:
      - wordpress
  
  cerbot:
   image: certbot/certbot
   container_name: cerbot
   env_file:
   - .env
   volumes:
   - ${CERTBOT_HOME}:/var/lib/letsencrypt
   - ${CERTBOT_CONFIG}:/etc/letsencrypt
   
networks:
  wordpress:
    name: wp-wordpress
    driver: bridge